### ISSUE TITLE
rtk diff command throws TypeError: fn is not a function from version 0.2.0

### ISSUE THREAD

**Issue by soukand** [IBM/report-toolkit#61]
```
Command: rtk diff report.20191113.145259.33449.0.001.json report.20191113.145259.33450.0.001.json

rtk diff <file1> <file2>

Diff two reports

Filter:
  --includeProp, -i  Include only properties (filter)                                        [array]
  --excludeProp, -x  Exclude properties (reject)                                             [array]
  --all              Include everything in diff                                            [boolean]

Output:
  --color                Use color output where applicable                 [boolean] [default: true]
  --output, -o           Output to file instead of STDOUT                                   [string]
  --show-secrets-unsafe  Live dangerously & do not automatically redact secrets            [boolean]
  --transform, -t        Transform(s) to apply
       [string] [choices: "csv", "filter", "json", "newline", "numeric", "table"] [default: "table"]

"json" Transform Options:
  --pretty  Pretty-print JSON output                                                       [boolean]

"table" Transform Options:
  --max-width  Set maximum output width; ignored if --no-truncate used
                                                                  [number] [default: terminal width]
  --truncate   Truncate & word-wrap output                                 [boolean] [default: true]

"filter" Transform Options:
  --exclude  Exclude properties (keypaths allowed)                            [string] [default: []]
  --include  Include properties (keypaths allowed)                            [string] [default: []]

Options:
  --debug, --verbose  Enable debug output                                                  [boolean]
  --rc                Custom file or directory path to .rtkrc.js                            [string]
  --help              Show help                                                            [boolean]
  --version           Show version number                                                  [boolean]

TypeError: fn is not a function
    at /Users/toomas/experiments/node-report/report/rtk/node_modules/rxjs/internal/util/pipe.js:20:56
    at Array.reduce (<anonymous>)
    at piped (/Users/toomas/experiments/node-report/report/rtk/node_modules/rxjs/internal/util/pipe.js:20:20)
    at Observable.pipe (/Users/toomas/experiments/node-report/report/rtk/node_modules/rxjs/internal/Observable.js:92:48)
    at Object.handler (/Users/toomas/experiments/node-report/report/rtk/node_modules/@report-toolkit/cli/dist/report-toolkit-cli.cjs.js:286:100)
    at /Users/toomas/experiments/node-report/report/rtk/node_modules/yargs/lib/command.js:241:49
```

diff command worked in version 0.1.3

**Comment by boneskull** [comment]
Fixed in [v0.2.2](https://github.com/IBM/report-toolkit/releases/tag/v0.2.2)
